import 'package:get/get.dart';

class AllItemsClass extends GetxController {
  List<Map> allItems = [
    {
      'icon': 'assets/icons/instagram.png',
      'title': 'Instagram',
      'route': 'InstagramScreen',
      'link': 'https://www.instagram.com/',
      'isLock': false.obs,
      'isPopular': true,
      'isSocial': true,
      'isMedia': false,
    },
    {
      'icon': 'assets/icons/facebook.png',
      'title': 'Facebook',
      'route': 'FacebookScreen',
      'link': 'https://m.facebook.com/',
      'isLock': false.obs,
      'isPopular': true,
      'isSocial': true,
      'isMedia': false,
    },
    {
      'icon': 'assets/icons/twitter.png',
      'title': 'Twitter',
      'route': 'TwitterScreen',
      'link': 'https://twitter.com/',
      'isLock': false.obs,
      'isPopular': true,
      'isSocial': true,
      'isMedia': false,
    },
    {
      'icon': 'assets/icons/pinterest.png',
      'title': 'Pinterest',
      'route': 'PinterestScreen',
      'link': 'https://www.pinterest.com/',
      'isLock': false.obs,
      'isPopular': true,
      'isSocial': true,
      'isMedia': true,
    },
    {
      'icon': 'assets/icons/vk.png',
      'title': 'ВКонтакте',
      'route': 'vkScreen',
      'link': 'https://m.vk.com/',
      'isLock': false.obs,
      'isPopular': true,
      'isSocial': true,
      'isMedia': false,
    },
    {
      'icon': 'assets/icons/linkedin.png',
      'title': 'LinkedIn',
      'route': 'LinkedInScreen',
      'link': 'https://www.linkedin.com/',
      'isLock': false.obs,
      'isPopular': true,
      'isSocial': true,
      'isMedia': false,
    },
    {
      'icon': 'assets/icons/reddit.png',
      'title': 'Reddit',
      'route': 'RedditScreen',
      'link': 'https://www.reddit.com/',
      'isLock': false.obs,
      'isPopular': false,
      'isSocial': true,
      'isMedia': false,
    },
    {
      'icon': 'assets/icons/tik-tok.png',
      'title': 'TikTok',
      'route': 'TikTokScreen',
      'link': 'https://www.tiktok.com/',
      'isLock': false.obs,
      'isPopular': true,
      'isSocial': false,
      'isMedia': true,
    },
    {
      'icon': 'assets/icons/letterboxd.png',
      'title': 'Letterboxd',
      'route': 'LetterboxdScreen',
      'link': 'https://letterboxd.com/',
      'isLock': false.obs,
      'isPopular': false,
      'isSocial': false,
      'isMedia': false,
    },
    {
      'icon': 'assets/icons/meetup.png',
      'title': 'Meetup',
      'route': 'MeetupScreen',
      'link': 'https://www.meetup.com/',
      'isLock': false.obs,
      'isPopular': false,
      'isSocial': true,
      'isMedia': false,
    },
    {
      'icon': 'assets/icons/youtube.png',
      'title': 'You Tube',
      'route': 'YouTubeScreen',
      'link': 'https://m.youtube.com/',
      'isLock': false.obs,
      'isPopular': true,
      'isSocial': false,
      'isMedia': true,
    },
    {
      'icon': 'assets/icons/quora.png',
      'title': 'Quora',
      'route': 'QuoraScreen',
      'link': 'https://www.quora.com/',
      'isLock': false.obs,
      'isPopular': false,
      'isSocial': false,
      'isMedia': true,
    },
    {
      'icon': 'assets/icons/tumblr.png',
      'title': 'Tumblr',
      'route': 'TumblrScreen',
      'link': 'https://www.tumblr.com/',
      'isLock': false.obs,
      'isPopular': false,
      'isSocial': true,
      'isMedia': false,
    },
    {
      'icon': 'assets/icons/flickr.png',
      'title': 'Flickr',
      'route': 'FlickrScreen',
      'link': 'https://www.flickr.com/',
      'isLock': false.obs,
      'isPopular': false,
      'isSocial': false,
      'isMedia': true,
    },
    {
      'icon': 'assets/icons/bigoLive.png',
      'title': 'Bigo Live',
      'route': 'BigoLiveScreen',
      'link': 'https://www.bigo.tv/',
      'isLock': false.obs,
      'isPopular': false,
      'isSocial': false,
      'isMedia': true,
    },
    {
      'icon': 'assets/icons/Likee.png',
      'title': 'Likee',
      'route': 'LikeeScreen',
      'link': 'https://likee.video/',
      'isLock': false.obs,
      'isPopular': true,
      'isSocial': false,
      'isMedia': true,
    },
    // {
    //   'icon': 'assets/icons/anesi_media.png',
    //   'title': 'Anesi Media',
    //   'route': 'app',
    //   'link': 'com.imusic.host',
    //   'isLock': false.obs,
    //   'isPopular': false,
    //   'isSocial': false,
    //   'isMedia': true,
    // },
    // {
    //   'icon': 'assets/icons/anesi_media_pro.png',
    //   'title': 'Anesi Media Pro',
    //   'route': 'app',
    //   'link': 'com.mix_music_pro.host',
    //   'isLock': false.obs,
    //   'isPopular': false,
    //   'isSocial': false,
    //   'isMedia': true,
    // },
  ].obs;
}
